version: '2'
services:
    shortcutmaster-app:
        image: shortcutmaster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shortcutmaster-postgresql:5432/shortcutmaster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shortcutmaster-postgresql:
        extends:
            file: postgresql.yml
            service: shortcutmaster-postgresql
